#!/bin/bash

# go to the retroverse directory, this should be a fixed path
cd /roms/retroverse

# pull latest changes from the repository
git pull

# cp and overwrite all pulled files into the retroverse system
rsync -a ./* /

# apply patches if any
chmod 755 -R /emuelec/scripts/
for file in /emuelec/scripts/patches/*; do
    echo "applying patch $file"
    "$file"
done

echo "Done. Please reboot the system so changes take effect!"
