#!/bin/bash

# go to the retroverse directory, this should be a fixed path
cd /storage/roms/retroverse

# pull latest changes from the repository
git pull

# cp and overwrite all pulled files into the retroverse system
rsync -a --exclude '.git' ./* /

# apply patches if any
chmod 755 -R /storage/.config/emuelec/scripts/
for file in /storage/.config/emuelec/scripts/patches/*; do
    echo "applying patch $file"
    "$file"
done

# write the current version
cd /storage/roms/retroverse
current_version=$(git rev-list --count HEAD)
echo "1.0$current_version" >/storage/.config/EE_VERSION

echo "Done. Please reboot the system so changes take effect!"
