#!/bin/bash

cd /storage/roms/retroverse

# check if any updates are available
if [ "$1" == "canupdate" ]; then
	git remote update &>/dev/null
	available=$(git status | grep "Your branch is behind" | sed 's/[^0-9]//g')

	if ! [[ $available =~ '^[0-9]+$' ]]; then
		echo "No updates are available" >&2
		exit 12
	else
		echo "$available updates are available" >&2
		exit 0
	fi
fi

# run the update script
chmod 755 -R ./storage/.config/emuelec/scripts
./storage/.config/emuelec/scripts/retroverse-update
