#!/bin/bash

cd /storage/roms/retroverse

# check if any updates are available
if [ "$1" == "canupdate" ]; then
	git remote update &>/dev/null
	available=$(git status | grep "Your branch is behind" | sed 's/[^0-9]//g')

	case $available in
		'' | *[!0-9]*)
			echo "No updates are available"
			exit 12
			;;
		*)
			echo "$available updates are available"
			exit 0
			;;
	esac
	# if ! [[ $available =~ ^-?[0-9]+$ ]]; then
	# 	echo "$available updates are available"
	# 	exit 0
	# else
	# 	echo "No updates are available"
	# 	exit 12
	# fi
fi

# run the update script
chmod 755 -R ./storage/.config/emuelec/scripts
./storage/.config/emuelec/scripts/retroverse-update
